from io import BytesIO
from datetime import date
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from .models import BookingRoom


def generate_invoice_pdf(booking, invoice_number):
    buffer = BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40,
    )

    styles = getSampleStyleSheet()
    story = []

    user = booking.user
    resort = booking.resort

    rooms = BookingRoom.objects.filter(booking=booking).select_related("room")

    room_list = ", ".join([r.room.room_number for r in rooms])

    issue_date = date.today().strftime("%d %b %Y")

    # ===== Header / Brand =====
    story.append(Paragraph("<b>Vintza by Vintage Resorts</b>", styles["Title"]))
    story.append(
        Paragraph(
            "<font size=11>Premium Resort Booking & Hospitality Services</font>",
            styles["Normal"],
        )
    )
    story.append(Spacer(1, 10))

    # Divider Line
    story.append(
        Paragraph(
            "<para backcolor='#DDDDDD' spaceb=6 spacea=6></para>", styles["Normal"]
        )
    )

    story.append(Spacer(1, 8))

    # ===== Invoice Summary =====
    summary_table = Table(
        [
            ["Invoice Number", f"{invoice_number}"],
            ["Invoice Date", issue_date],
            ["Booking ID", f"{booking.id}"],
            ["Payment Status", booking.status.title()],
        ],
        colWidths=[130, 300],
    )

    summary_table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.whitesmoke),
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.grey),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
            ]
        )
    )

    story.append(summary_table)
    story.append(Spacer(1, 15))

    # ===== Customer Details =====
    story.append(Paragraph("<b>Bill To</b>", styles["Heading3"]))

    customer_table = Table(
        [
            ["Guest Name", user.name or user.username],
            ["Phone", getattr(user, "phone_number", "")],
            ["Email", user.email or "-"],
        ],
        colWidths=[130, 300],
    )

    customer_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ]
        )
    )

    story.append(customer_table)
    story.append(Spacer(1, 15))

    # ===== Booking Details =====
    story.append(Paragraph("<b>Booking Details</b>", styles["Heading3"]))

    booking_table = Table(
        [
            ["Resort", resort.name],
            ["Location", resort.location],
            ["Check-In", booking.check_in.strftime("%d %b %Y")],
            ["Check-Out", booking.check_out.strftime("%d %b %Y")],
            ["Rooms", room_list or "-"],
        ],
        colWidths=[130, 300],
    )

    booking_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ]
        )
    )

    story.append(booking_table)
    story.append(Spacer(1, 15))

    # ===== Payment Section =====
    story.append(Paragraph("<b>Payment Summary</b>", styles["Heading3"]))

    payment = booking.payment

    payment_table = Table(
        [
            ["Payment Type", payment.type.title()],
            ["Provider", payment.provider],
            ["Transaction ID", payment.provider_payment_id],
            ["Amount Paid", f"₹{payment.amount}"],
        ],
        colWidths=[130, 300],
    )

    payment_table.setStyle(
        TableStyle(
            [
                ("BOX", (0, 0), (-1, -1), 1, colors.black),
                ("INNERGRID", (0, 0), (-1, -1), 0.4, colors.grey),
            ]
        )
    )

    story.append(payment_table)
    story.append(Spacer(1, 20))

    # ===== Footer Note =====
    story.append(
        Paragraph(
            "<i>This invoice is generated by Vintza by Vintage Resorts "
            "for booking confirmation and record purposes.</i>",
            styles["Normal"],
        )
    )

    doc.build(story)
    buffer.seek(0)
    return buffer
