# Generated by Django 6.0 on 2025-12-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_roomimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='aminities',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='resort',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_aminities',
            field=models.TextField(blank=True, null=True),
        ),
    ]
