# Generated by Django 5.0.13 on 2025-12-27 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_coupen_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='type',
            field=models.CharField(choices=[('partial', 'Partial'), ('full', 'Full')], default='full', max_length=50),
            preserve_default=False,
        ),
    ]
