# Generated by Django 6.0 on 2025-12-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_payment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resort',
            name='contact_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
